<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerQPWNpZe\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerQPWNpZe/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerQPWNpZe.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerQPWNpZe\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerQPWNpZe\App_KernelDevDebugContainer([
    'container.build_hash' => 'QPWNpZe',
    'container.build_id' => '7b6d2f28',
    'container.build_time' => 1588256189,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerQPWNpZe');
